In [5]:
#单位矩阵
import numpy as np
arr=np.eye(3,4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [7]:
#主对角线元素不为0的数值
arr=np.diag([1,5,2,3])
print(arr)

[[1 0 0 0]
 [0 5 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [9]:
# 随机生成0-1的浮点数
arr=np.random.rand(3,4)
print(arr)

[[0.22541257 0.51925239 0.86787219 0.64269987]
 [0.93081504 0.94840959 0.79065159 0.24332548]
 [0.41968618 0.15124443 0.95653262 0.87015133]]


In [12]:
#生成指定范围区间的随机浮点数
arr=np.random.uniform(3,6,(2,3))
print(arr)

[[4.66281512 5.95548177 5.55460785]
 [5.83914244 3.62453078 5.53198068]]


In [13]:
#生成指定范围的随机整数
arr=np.random.randint(3,30,(3,4))
print(arr)

[[ 9  8 13  8]
 [10 28  9 20]
 [22 14 27 10]]


In [14]:
#生成随机数列（正态分布）
arr=np.random.randn(3,4)
print(arr)

[[ 1.6433913   0.56264762 -0.78092502 -0.34663332]
 [ 0.25082852 -0.25724253  1.28341955 -0.18412478]
 [-0.28284939 -1.58312907 -1.57518705 -1.83043899]]


In [19]:
#设置随机种子
np.random.seed(10)
arr=np.random.randint(1,20,(2,3))
print(arr)

[[10  5 16]
 [ 1 18 17]]


In [21]:
arr=np.array([1,0,5,0],dtype='bool')
print(arr)

[ True False  True False]


In [27]:
arr=np.array([1,0,5,128],dtype='int16')
print(arr)

[  1   0   5 128]


In [34]:
#等差数列（start，stop，step）
arr=np.arange(1,10,1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [33]:
#（start，stop，num）共生成num个元素
arr=np.linspace(1,10,5,dtype=int)
print(arr)

[ 1  3  5  7 10]


In [36]:
#一维数组索引与切片
arr=np.random.randint(1,100,20)
print(arr)

[ 9 74  1 41 37 17 12 55 89 63 34 73 79 50 52 55 78 70 14 26]


In [44]:
print(arr[0])
print(arr[:])
print(arr[2:7])#左包右不包
print(arr[slice(2,7)])
print(arr[slice(2,7,3)])
print(arr[(arr>10)&(arr<70)])#布尔索引


9
[ 9 74  1 41 37 17 12 55 89 63 34 73 79 50 52 55 78 70 14 26]
[ 1 41 37 17 12]
[ 1 41 37 17 12]
[ 1 17]
[41 37 17 12 55 63 34 50 52 55 14 26]


In [57]:
arr=np.random.randint(1,100,(4,8))
print(arr)

[[14 93 87 31 31 90 13 66]
 [32 58 37 28 19 94 78 23]
 [24 95 12 29 75 89 10 16]
 [19 81 72 89 12 18 47  8]]


In [68]:
print(arr[1,2])
print(arr[2,2:5])
print(arr[arr<50])
print(arr[2][arr[2]>50])

37
[12 29 75]
[14 31 31 13 32 37 28 19 23 24 12 29 10 16 19 12 18 47  8]
[95 75 89]
