In [5]:
#单位矩阵
import numpy as np
arr=np.eye(3,4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [7]:
#主对角线元素不为0的数值
arr=np.diag([1,5,2,3])
print(arr)

[[1 0 0 0]
 [0 5 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [9]:
# 随机生成0-1的浮点数
arr=np.random.rand(3,4)
print(arr)

[[0.22541257 0.51925239 0.86787219 0.64269987]
 [0.93081504 0.94840959 0.79065159 0.24332548]
 [0.41968618 0.15124443 0.95653262 0.87015133]]


In [12]:
#生成指定范围区间的随机浮点数
arr=np.random.uniform(3,6,(2,3))
print(arr)

[[4.66281512 5.95548177 5.55460785]
 [5.83914244 3.62453078 5.53198068]]


In [13]:
#生成指定范围的随机整数
arr=np.random.randint(3,30,(3,4))
print(arr)

[[ 9  8 13  8]
 [10 28  9 20]
 [22 14 27 10]]


In [14]:
#生成随机数列（正态分布）
arr=np.random.randn(3,4)
print(arr)

[[ 1.6433913   0.56264762 -0.78092502 -0.34663332]
 [ 0.25082852 -0.25724253  1.28341955 -0.18412478]
 [-0.28284939 -1.58312907 -1.57518705 -1.83043899]]


In [19]:
#设置随机种子
np.random.seed(10)
arr=np.random.randint(1,20,(2,3))
print(arr)

[[10  5 16]
 [ 1 18 17]]


In [21]:
arr=np.array([1,0,5,0],dtype='bool')
print(arr)

[ True False  True False]


In [27]:
arr=np.array([1,0,5,128],dtype='int16')
print(arr)

[  1   0   5 128]


In [34]:
#等差数列（start，stop，step）
arr=np.arange(1,10,1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [33]:
#（start，stop，num）共生成num个元素
arr=np.linspace(1,10,5,dtype=int)
print(arr)

[ 1  3  5  7 10]


In [36]:
#一维数组索引与切片
arr=np.random.randint(1,100,20)
print(arr)

[ 9 74  1 41 37 17 12 55 89 63 34 73 79 50 52 55 78 70 14 26]


In [44]:
print(arr[0])
print(arr[:])
print(arr[2:7])#左包右不包
print(arr[slice(2,7)])
print(arr[slice(2,7,3)])
print(arr[(arr>10)&(arr<70)])#布尔索引


9
[ 9 74  1 41 37 17 12 55 89 63 34 73 79 50 52 55 78 70 14 26]
[ 1 41 37 17 12]
[ 1 41 37 17 12]
[ 1 17]
[41 37 17 12 55 63 34 50 52 55 14 26]


In [57]:
arr=np.random.randint(1,100,(4,8))
print(arr)

[[14 93 87 31 31 90 13 66]
 [32 58 37 28 19 94 78 23]
 [24 95 12 29 75 89 10 16]
 [19 81 72 89 12 18 47  8]]


In [68]:
print(arr[1,2])
print(arr[2,2:5])
print(arr[arr<50])
print(arr[2][arr[2]>50])

37
[12 29 75]
[14 31 31 13 32 37 28 19 23 24 12 29 10 16 19 12 18 47  8]
[95 75 89]


In [22]:
#数组算术运算
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [17]:
#列表
c=[1,2,3]
d=[4,5,6]
print(c+d)
for i in range(len(c)):
  print(c[i])
  d[i]=d[i]+c[i]
print(d)

[1, 2, 3, 4, 5, 6]
1
2
3
[5, 7, 9]


In [24]:
#数组与标量之间的运算
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+3)
print(a*3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [26]:
#广播机制：维度相同，总有1
a=np.array([1,2,3])#1行3列
b=np.array([[4],[5],[6]])#3行1列
print(a+b)
print(b-a)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


In [28]:
#矩阵运算
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a@b)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


In [ ]:
#numpy中常用函数
基本数学函数

In [29]:
#指数 默认以e为底e**x
print(np.exp(0))

1.0


In [30]:
#自然对数
print(np.log(2.71))

0.9969486348916096


In [33]:
#三角函数
print(np.sin(1))
print(np.cos(np.pi))

0.8414709848078965
-1.0


In [34]:
#绝对值
arr=np.array([-1,1,2,-3])
print(np.abs(arr))

[1 1 2 3]


In [35]:
#计算a的b次幂
print(np.power(arr,2))

[1 1 4 9]


In [39]:
#四舍五入
print(np.round([3.2,4.5,8.1,7.9]))

[3. 4. 8. 8.]


In [41]:
#向上取整，向下取整
arr=np.array([1.6,25.1,81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [45]:
#检测缺失值nan
np.isnan([2,2,3,np.nan])

array([False, False, False,  True])